### ISSUE TITLE
Error: getUser - status code is: 50X ::: FetchError: invalid json response body

### ISSUE THREAD

**Issue by GastonGit** [GastonGit/Hot-Twitch-Clips.Client#125]
```
2021-06-08T10:00:21: ^[[31mclipIt :: Error: getUser - status code is: 502^[[0m
2021-06-08T10:01:10: ^[[31mclipIt :: Error: getUser - status code is: 502^[[0m
2021-06-08T10:02:52: ^[[31mclipIt :: Error: getUser - status code is: 500^[[0m
2021-06-08T10:05:40: ^[[31mclipIt :: Error: getUser - status code is: 502^[[0m
2021-06-08T10:18:03: ^[[31mclipIt :: Error: getUser - status code is: 503^[[0m
2021-06-08T10:24:51:
2021-06-08T10:24:51: .../Hot-Twitch-Clips/server/node_modules/node-fetch/lib/index.js:272
2021-06-08T10:24:51:                            return Body.Promise.reject(new FetchError(`invalid json response body at ${_this2.url} reason: ${err.message}`, 'invalid-json'));
2021-06-08T10:24:51:                                                       ^
2021-06-08T10:24:51: FetchError: invalid json response body at https://api.twitch.tv/helix/clips?id=BeautifulHonestLionTheRinger-_9Q8e08Vyfp7wy4k reason: Unexpected token I in JSON at position 0
2021-06-08T10:24:51:     at .../Hot-Twitch-Clips/server/node_modules/node-fetch/lib/index.js:272:32
2021-06-08T10:24:51:     at runMicrotasks (<anonymous>)
2021-06-08T10:24:51:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
2021-06-08T10:24:51:     at async Clipper.getClip (.../Hot-Twitch-Clips/server/lib/Clipper.js:68:24)
2021-06-08T10:24:51:     at async Clipper.getVideoUrl (.../Hot-Twitch-Clips/server/lib/Clipper.js:76:22)
2021-06-08T10:24:51:     at async HotClipsController.<anonymous> (.../Hot-Twitch-Clips/server/lib/HotClipsController.js:113:30) {
2021-06-08T10:24:51:   type: 'invalid-json'
2021-06-08T10:24:51: }
2021-06-08T10:29:09: ^[[31mclipIt :: Error: getUser - status code is: 503^[[0m
2021-06-08T10:29:15: ^[[31mclipIt :: Error: getUser - status code is: 502^[[0m
2021-06-08T10:33:14: ^[[31mclipIt :: Error: getUser - status code is: 503^[[0m
2021-06-08T10:37:39: ^[[31mclipIt :: Error: getUser - status code is: 502^[[0m
2021-06-08T10:40:20: ^[[31mclipIt :: Error: getUser - status code is: 502^[[0m
2021-06-08T10:43:00:
2021-06-08T10:43:00: .../Hot-Twitch-Clips/server/node_modules/node-fetch/lib/index.js:272
2021-06-08T10:43:00:                            return Body.Promise.reject(new FetchError(`invalid json response body at ${_this2.url} reason: ${err.message}`, 'invalid-json'));
2021-06-08T10:43:00:                                                       ^
2021-06-08T10:43:00: FetchError: invalid json response body at https://api.twitch.tv/helix/clips?id=TubularVibrantCroissantPanicVis-KEf8N2_oH4Ymjw6A reason: Unexpected token < in JSON at position 1
2021-06-08T10:43:00:     at .../Hot-Twitch-Clips/server/node_modules/node-fetch/lib/index.js:272:32
2021-06-08T10:43:00:     at runMicrotasks (<anonymous>)
2021-06-08T10:43:00:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
2021-06-08T10:43:00:     at async Clipper.getClip (.../Hot-Twitch-Clips/server/lib/Clipper.js:68:24)
2021-06-08T10:43:00:     at async Clipper.getVideoUrl (.../Hot-Twitch-Clips/server/lib/Clipper.js:76:22)
2021-06-08T10:43:00:     at async HotClipsController.<anonymous> (.../Hot-Twitch-Clips/server/lib/HotClipsController.js:113:30) {
2021-06-08T10:43:00:   type: 'invalid-json'
2021-06-08T10:43:00: }
2021-06-08T10:50:35: ^[[31mclipIt :: `Error: getUser - status code is: 500`^[[0m
2021-06-08T10:52:40: ^[[31mclipIt :: Error: getUser - status code is: 500^[[0m
2021-06-08T10:56:34: ^[[31mclipIt :: Error: getUser - status code is: 500^[[0m
2021-06-08T11:35:53:
2021-06-08T11:35:53: .../Hot-Twitch-Clips/server/node_modules/node-fetch/lib/index.js:272
2021-06-08T11:35:53:                            return Body.Promise.reject(new FetchError(`invalid json response body at ${_this2.url} reason: ${err.message}`, 'invalid-json'));
2021-06-08T11:35:53:                                                       ^
2021-06-08T11:35:53: FetchError: invalid json response body at https://api.twitch.tv/helix/clips?id=BenevolentAverageJellyfishKeyboardCat-_HELB9aMTyGD8Gxc reason: Unexpected token < in JSON at position 1
2021-06-08T11:35:53:     at .../Hot-Twitch-Clips/server/node_modules/node-fetch/lib/index.js:272:32
2021-06-08T11:35:53:     at runMicrotasks (<anonymous>)
2021-06-08T11:35:53:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
2021-06-08T11:35:53:     at async Clipper.getClip (.../Hot-Twitch-Clips/server/lib/Clipper.js:68:24)
2021-06-08T11:35:53:     at async Clipper.getVideoUrl (.../Hot-Twitch-Clips/server/lib/Clipper.js:76:22)
2021-06-08T11:35:53:     at async HotClipsController.<anonymous> (.../Hot-Twitch-Clips/server/lib/HotClipsController.js:113:30) {
2021-06-08T11:35:53:   type: 'invalid-json'
2021-06-08T11:35:53: }
2021-06-08T11:35:54:
2021-06-08T11:35:54: .../Hot-Twitch-Clips/server/node_modules/node-fetch/lib/index.js:272
2021-06-08T11:35:54:                            return Body.Promise.reject(new FetchError(`invalid json response body at ${_this2.url} reason: ${err.message}`, 'invalid-json'));
2021-06-08T11:35:54:                                                       ^
2021-06-08T11:35:54: FetchError: invalid json response body at https://api.twitch.tv/helix/streams?first=100&language=en reason: Unexpected token < in JSON at position 1
2021-06-08T11:35:54:     at .../Hot-Twitch-Clips/server/node_modules/node-fetch/lib/index.js:272:32
2021-06-08T11:35:54:     at processTicksAndRejections (node:internal/process/task_queues:96:5)
2021-06-08T11:35:54:     at async MonitorTwitchChat.request100Streams (.../Hot-Twitch-Clips/server/lib/MonitorTwitchChat.js:163:16)
2021-06-08T11:35:54:     at async MonitorTwitchChat.requestStreams (.../Hot-Twitch-Clips/server/lib/MonitorTwitchChat.js:130:36)
2021-06-08T11:35:54:     at async MonitorTwitchChat.updateStreamList (.../Hot-Twitch-Clips/server/lib/MonitorTwitchChat.js:121:27)
2021-06-08T11:35:54:     at async HotClipsController.setupConnection (.../Hot-Twitch-Clips/server/lib/HotClipsController.js:49:9) {
2021-06-08T11:35:54:   type: 'invalid-json'
2021-06-08T11:35:54: }
2021-06-09T01:31:27: ^[[31mclipIt :: FetchError: request to https://api.twitch.tv/helix/clips?broadcaster_id=51496027 failed, reason: connect ETIMEDOUT 151.101.14.214:443^[[0m
2021-06-10T00:04:23: ^[[31mclipIt :: FetchError: request to https://api.twitch.tv/helix/clips?broadcaster_id=207813352 failed, reason: connect ETIMEDOUT 151.101.14.214:443^[[0m
```

**Comment by GastonGit** [comment]
"Bad" status codes should not be throwing errors and will remove high prio since the error is rare

**Comment by GastonGit** [comment]
Moved to https://github.com/GastonGit/Hot-Twitch-Clips.Server/issues/6
